### ISSUE TITLE
with gulp intregration uglify-php

### ISSUE THREAD

**Issue by zahedhq** [flavior121/uglify-php#4]
can i do it with gulp, what is the code sample

**Comment by isflavior** [comment]
Hi.
Yes you can use it with Gulp. Try this:
```javascript
const gulp = require("gulp");
const UglifyPHP = require("uglify-php");
const through = require("through2");

gulp.task("minify", function () {
      return gulp.src("test.php")
      .pipe(through.obj(function (chunk, enc, cb) {
            UglifyPHP.minify(chunk.path).then(function (source) {
                  chunk.contents = new Buffer(source);
                  cb(null, chunk);
            });
      }))
      .pipe(gulp.dest("output_path"));
});
```

**Comment by zahedhq** [comment]
what about this, how to write this? 
  "minify": {
	 "replace_variables": true,
	 "remove_whitespace": true,
	 "remove_comments": true,
	 "minify_html": true
  },

**Comment by isflavior** [comment]
@zitengine 

You can use options on the _UglifyPHP.minify_ function:

`UglifyPHP.minify(chunk.path, OPTIONS_HERE).then(function (source) {`

**Comment by zahedhq** [comment]
Not Working, is it correct?
    UglifyPHP = require('uglify-php'),
    through = require('through2'),
gulp.task("phpminify", function () {
      return gulp.src(source + '**/*.php')
      .pipe(through.obj(function (chunk, enc, cb) {
            UglifyPHP.minify(chunk.path (

"replace_variables": true,
"remove_whitespace": true,
"remove_comments": true,
"minify_html": true
                )).then(function (source) {
                  chunk.contents = new Buffer(source);
                  cb(null, chunk);
            });
      }))
    .pipe(gulp.dest(dest));
});

**Comment by isflavior** [comment]
@zitengine the UglifyPHP call should be:

```javascript
UglifyPHP.minify(chunk.path, {
    "minify": {
        "replace_variables": true,
        "remove_whitespace": true,
        "remove_comments": true,
        "minify_html": true
    }
}).then(function (source) {
    chunk.contents = new Buffer(source);
    cb(null, chunk);
});
```
